version: '3.8'
services:
  postgres:
    image: db
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
      target: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gaszg54wqYhzgyKasY
  app:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_read
      POSTGRES_PASSWORD: fmkdlaojkl45F
      POSTGRES_URL: postgres
    ports:
      - "8000:8000"
