

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_25 = Integer(25); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_42 = Integer(42)
import random
import binascii
import sys

# From https://github.com/pwang00/Cryptographic-Attacks/blob/master/Public%20Key/RSA/coppersmith_short_pad.sage?utm_source=chatgpt.com
def coppersmith_short_pad(C1, C2, N, e, eps = _sage_const_1 /_sage_const_25 ):
    P = PolynomialRing(Zmod(N), names=('x', 'y',)); (x, y,) = P._first_ngens(2)
    P2 = PolynomialRing(Zmod(N), names=('y',)); (y,) = P2._first_ngens(1)

    g1 = (x**e - C1).change_ring(P2)
    g2 = ((x + y)**e - C2).change_ring(P2)
 
    # Changes the base ring to Z_N[y] and finds resultant of g1 and g2 in x
    res = g1.resultant(g2, variable=x)

    # coppersmith's small_roots only works over univariate polynomial rings, so we 
    # convert the resulting polynomial to its univariate form and take the coefficients modulo N
    # Then we can call the sage's small_roots function and obtain the delta between m_1 and m_2.
    # Play around with these parameters: (epsilon, beta, X)
    roots = res.univariate_polynomial().change_ring(Zmod(N))        .small_roots(epsilon=eps)

    return roots[_sage_const_0 ]
def franklin_reiter(C1, C2, N, r, e):
    P = PolynomialRing(Zmod(N), names=('x',)); (x,) = P._first_ngens(1)
    equations = [x ** e - C1, (x + r) ** e - C2]
    g1, g2 = equations
    return -composite_gcd(g1,g2).coefficients()[_sage_const_0 ]
def recover_message(C1, C2, N, e):
    delta = coppersmith_short_pad(C1, C2, N, e=e)
    recovered = franklin_reiter(C1, C2, N, delta, e=e)
    return recovered
def composite_gcd(g1,g2):
    return g1.monic() if g2 == _sage_const_0  else composite_gcd(g2, g1 % g2)
##

C1, C2, N = [int(x) for x in sys.argv[_sage_const_1 :]]
print(recover_message(C1, C2, N, _sage_const_3 )>>_sage_const_42 )


